# Используем актуальную версию синтаксиса
version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Оставляем для DBeaver/DataGrip
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    depends_on:
      - backend
    networks:
      - my_network

  # НОВЫЙ СЕРВИС: Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80" # Слушаем стандартный HTTP порт на хост-машине
    volumes:
      # Пробрасываем конфиг внутрь контейнера
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge