const data = [
    {   
        id: 'model1',
        url: 'veronika',
        title: 'Veronika',
        description: '',
        images: [
            { id: 1, src: '/assets/image/model/veronika/1.jpg' },
            { id: 2, src: '/assets/image/model/veronika/2.jpg' },
            { id: 3, src: '/assets/image/model/veronika/3.jpg' },
            { id: 4, src: '/assets/image/model/veronika/4.jpg' },
            { id: 5, src: '/assets/image/model/veronika/5.jpg' },
            { id: 6, src: '/assets/image/model/veronika/6.jpg' },
            { id: 7, src: '/assets/image/model/veronika/7.jpg' },
            { id: 8, src: '/assets/image/model/veronika/8.jpg' },
            { id: 9, src: '/assets/image/model/veronika/9.jpg' },
            { id: 10, src: '/assets/image/model/veronika/10.jpg' },
            { id: 11, src: '/assets/image/model/veronika/11.jpg' },
            { id: 12, src: '/assets/image/model/veronika/12.jpg' },
            { id: 13, src: '/assets/image/model/veronika/13.jpg' },
            { id: 14, src: '/assets/image/model/veronika/14.jpg' },
            { id: 15, src: '/assets/image/model/veronika/15.jpg' },
            { id: 16, src: '/assets/image/model/veronika/16.jpg' },
            { id: 17, src: '/assets/image/model/veronika/17.jpg' },
            { id: 18, src: '/assets/image/model/veronika/18.jpg' },
            { id: 19, src: '/assets/image/model/veronika/19.jpg' },
            { id: 20, src: '/assets/image/model/veronika/20.jpg' },
            { id: 21, src: '/assets/image/model/veronika/21.jpg' },
            { id: 22, src: '/assets/image/model/veronika/22.jpg' },
            { id: 23, src: '/assets/image/model/veronika/23.jpg' },
            { id: 24, src: '/assets/image/model/veronika/24.jpg' },
            { id: 25, src: '/assets/image/model/veronika/25.jpg' }
        ]
    },
    {
        id: 'model2',
        url: 'nastya',
        title: 'Nastya',
        description: 'Description for Model 2 with key features and specifications.',
        images: [
            { id: 1, src: '/assets/image/model/nastya/1.jpg' },
            { id: 2, src: '/assets/image/model/nastya/2.jpg' },
            { id: 3, src: '/assets/image/model/nastya/3.jpg' },
            { id: 4, src: '/assets/image/model/nastya/4.jpg' },
            { id: 5, src: '/assets/image/model/nastya/5.jpg' },
            { id: 6, src: '/assets/image/model/nastya/6.jpg' },
            { id: 7, src: '/assets/image/model/nastya/7.jpg' },
            { id: 8, src: '/assets/image/model/nastya/8.jpg' },
            { id: 9, src: '/assets/image/model/nastya/9.jpg' },
            { id: 10, src: '/assets/image/model/nastya/10.jpg' },
            { id: 11, src: '/assets/image/model/nastya/11.jpg' },
            { id: 12, src: '/assets/image/model/nastya/12.jpg' },
            { id: 13, src: '/assets/image/model/nastya/13.jpg' },
            { id: 14, src: '/assets/image/model/nastya/14.jpg' },
            { id: 15, src: '/assets/image/model/nastya/15.jpg' },
            { id: 16, src: '/assets/image/model/nastya/16.jpg' },
            { id: 17, src: '/assets/image/model/nastya/17.jpg' },
            { id: 18, src: '/assets/image/model/nastya/18.jpg' },
            { id: 19, src: '/assets/image/model/nastya/19.jpg' },
            { id: 20, src: '/assets/image/model/nastya/20.jpg' }
        ]
    },
    {
        id: 'model3',
        url: 'angelina',
        title: 'Angelina',
        description: 'Description for Model 3 with key features and specifications.',
        images: [
            { id: 1, src: '/assets/image/model/angelina/1.jpg' },
            { id: 2, src: '/assets/image/model/angelina/2.jpg' },
            { id: 3, src: '/assets/image/model/angelina/3.jpg' },
            { id: 4, src: '/assets/image/model/angelina/4.jpg' },
            { id: 5, src: '/assets/image/model/angelina/5.jpg' },
            { id: 6, src: '/assets/image/model/angelina/6.jpg' },
            { id: 7, src: '/assets/image/model/angelina/7.jpg' },
            { id: 8, src: '/assets/image/model/angelina/8.jpg' },
            { id: 9, src: '/assets/image/model/angelina/9.jpg' },
            { id: 10, src: '/assets/image/model/angelina/10.jpg' },
            { id: 11, src: '/assets/image/model/angelina/11.jpg' },
            { id: 12, src: '/assets/image/model/angelina/12.jpg' },
            { id: 13, src: '/assets/image/model/angelina/13.jpg' },
            { id: 14, src: '/assets/image/model/angelina/14.jpg' },
            { id: 15, src: '/assets/image/model/angelina/15.jpg' },
            { id: 16, src: '/assets/image/model/angelina/16.jpg' },
            { id: 17, src: '/assets/image/model/angelina/17.jpg' },
            { id: 18, src: '/assets/image/model/angelina/18.jpg' },
            { id: 19, src: '/assets/image/model/angelina/19.jpg' },
            { id: 20, src: '/assets/image/model/angelina/20.jpg' },
            { id: 21, src: '/assets/image/model/angelina/21.jpg' },
            { id: 22, src: '/assets/image/model/angelina/22.jpg' }
        ]
    },
    {   
        id: 'model4',
        url: 'anastasia',
        title: 'Anastasia',
        description: 'Description for Model 1 with key features and specifications.',
        images: [
            { id: 1, src: '/assets/image/model/anastasia/1.jpg' },
            { id: 2, src: '/assets/image/model/anastasia/2.jpg' },
            { id: 3, src: '/assets/image/model/anastasia/3.jpg' },
            { id: 4, src: '/assets/image/model/anastasia/4.jpg' },
            { id: 5, src: '/assets/image/model/anastasia/5.jpg' },
            { id: 6, src: '/assets/image/model/anastasia/6.jpg' },
            { id: 7, src: '/assets/image/model/anastasia/7.jpg' },
            { id: 8, src: '/assets/image/model/anastasia/8.jpg' },
            { id: 9, src: '/assets/image/model/anastasia/9.jpg' },
            { id: 10, src: '/assets/image/model/anastasia/10.jpg' },
            { id: 11, src: '/assets/image/model/anastasia/11.jpg' },
            { id: 12, src: '/assets/image/model/anastasia/12.jpg' },
            { id: 13, src: '/assets/image/model/anastasia/13.jpg' },
            { id: 14, src: '/assets/image/model/anastasia/14.jpg' },
            { id: 15, src: '/assets/image/model/anastasia/15.jpg' },
            { id: 16, src: '/assets/image/model/anastasia/16.jpg' },
            { id: 17, src: '/assets/image/model/anastasia/17.jpg' },
            { id: 18, src: '/assets/image/model/anastasia/18.jpg' },
            { id: 19, src: '/assets/image/model/anastasia/19.jpg' },
            { id: 20, src: '/assets/image/model/anastasia/20.jpg' },
            { id: 21, src: '/assets/image/model/anastasia/21.jpg' },
            { id: 22, src: '/assets/image/model/anastasia/22.jpg' },
            { id: 23, src: '/assets/image/model/anastasia/23.jpg' },
            { id: 24, src: '/assets/image/model/anastasia/24.jpg' },
            { id: 25, src: '/assets/image/model/anastasia/25.jpg' },
            { id: 26, src: '/assets/image/model/anastasia/26.jpg' },
            { id: 27, src: '/assets/image/model/anastasia/27.jpg' }

        ]
    },
    {   
        id: 'model5',
        url: 'vadim',
        title: 'Vadim',
        description: 'Description for Model 1 with key features and specifications.',
        images: [
            { id: 1, src: '/assets/image/model/vadim/1.jpg' },
            { id: 2, src: '/assets/image/model/vadim/2.jpg' },
            { id: 3, src: '/assets/image/model/vadim/3.jpg' },
            { id: 4, src: '/assets/image/model/vadim/4.jpg' },
            { id: 5, src: '/assets/image/model/vadim/5.jpg' },
            { id: 6, src: '/assets/image/model/vadim/6.jpg' },
            { id: 7, src: '/assets/image/model/vadim/7.jpg' },
            { id: 8, src: '/assets/image/model/vadim/8.jpg' },
            { id: 9, src: '/assets/image/model/vadim/9.jpg' },
            { id: 10, src: '/assets/image/model/vadim/10.jpg' },
            { id: 11, src: '/assets/image/model/vadim/11.jpg' },
            { id: 12, src: '/assets/image/model/vadim/12.jpg' },
            { id: 13, src: '/assets/image/model/vadim/13.jpg' },
            { id: 14, src: '/assets/image/model/vadim/14.jpg' },
            { id: 15, src: '/assets/image/model/vadim/15.jpg' }

        ]
    },
    {   
        id: 'model6',
        url: 'elia-artem',
        title: 'Elia',
        description: 'Description for Model 1 with key features and specifications.',
        images: [
            { id: 1, src: '/assets/image/model/elia&artem/1.jpg' },
            { id: 2, src: '/assets/image/model/elia&artem/2.jpg' },
            { id: 3, src: '/assets/image/model/elia&artem/3.jpg' },
            { id: 4, src: '/assets/image/model/elia&artem/4.jpg' },
            { id: 5, src: '/assets/image/model/elia&artem/5.jpg' },
            { id: 6, src: '/assets/image/model/elia&artem/6.jpg' },
            { id: 7, src: '/assets/image/model/elia&artem/7.jpg' },
            { id: 8, src: '/assets/image/model/elia&artem/8.jpg' },
            { id: 9, src: '/assets/image/model/elia&artem/9.jpg' },
            { id: 10, src: '/assets/image/model/elia&artem/10.jpg' },
            { id: 11, src: '/assets/image/model/elia&artem/11.jpg' },
            { id: 12, src: '/assets/image/model/elia&artem/12.jpg' },
            { id: 13, src: '/assets/image/model/elia&artem/13.jpg' },
            { id: 14, src: '/assets/image/model/elia&artem/14.jpg' },
            { id: 15, src: '/assets/image/model/elia&artem/15.jpg' },
            { id: 16, src: '/assets/image/model/elia&artem/16.jpg' },
            { id: 17, src: '/assets/image/model/elia&artem/17.jpg' },
            { id: 18, src: '/assets/image/model/elia&artem/18.jpg' },
            { id: 19, src: '/assets/image/model/elia&artem/19.jpg' },
            { id: 20, src: '/assets/image/model/elia&artem/20.jpg' },
            { id: 21, src: '/assets/image/model/elia&artem/21.jpg' },
            { id: 22, src: '/assets/image/model/elia&artem/22.jpg' },
            { id: 23, src: '/assets/image/model/elia&artem/23.jpg' },
            { id: 24, src: '/assets/image/model/elia&artem/24.jpg' },
            { id: 25, src: '/assets/image/model/elia&artem/25.jpg' },
            { id: 26, src: '/assets/image/model/elia&artem/26.jpg' },
            { id: 27, src: '/assets/image/model/elia&artem/27.jpg' },
            { id: 28, src: '/assets/image/model/elia&artem/28.jpg' },
            { id: 29, src: '/assets/image/model/elia&artem/29.jpg' },
            { id: 30, src: '/assets/image/model/elia&artem/30.jpg' },
            { id: 31, src: '/assets/image/model/elia&artem/31.jpg' },
            { id: 32, src: '/assets/image/model/elia&artem/32.jpg' },
            { id: 33, src: '/assets/image/model/elia&artem/33.jpg' },
            { id: 34, src: '/assets/image/model/elia&artem/34.jpg' }
        ]
    },
    
];

export default data;